### PR TITLE
Serious theme

### PR DESCRIPTION
**Pull request by mrjovanovic**
I made two commits because like an idiot I used symlinks instead of hardlinks between my theme repo and this forked one. It should be fine now.

### CODE REVIEW

**Comment by nodiscc** [comment]
@mrjovanovic everything looks fine overall; though I'd prefer having only 1 commit.

Do you know how to rebase and squash commits (groups these 2 commits as only 1)? There's an easy tutorial [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) if you're interested. Otherwise let me know and I'll do it.

Basically you just have to

```
git checkout SeriousTheme
git rebase -i HEAD~2
# in the editor, pick the first commit, squash the second ... then
git push -f #will overwrite your github repo state with the new rebased one
```

**Comment by mrjovanovic** [comment]
Thanks, that's a very useful link. I have to learn not to commit so eagerly! Really appreciate your help, you're great. Hope that's better now.

**Comment by nodiscc** [comment]
Testing this in the coming days, thanks for your work.

**Comment by nodiscc** [comment]
Sorry for taking so long. I just merged your theme in https://github.com/shaarli/shaarli-themes/commit/29050cd99f692c47778afb8610f958ea4da8302a

**Pull request closed without merging**
